import { Countries } from "src/app/interfaces/country.model";

export var countries: Countries [] =  [
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}
{id: , name: ''}]
