// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TEC_KasinoAPI.Data;

#nullable disable

namespace TEC_KasinoAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220224132718_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TEC_KasinoAPI.Models.AccountBalance", b =>
                {
                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<double>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("0");

                    b.Property<int>("DepositLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1000");

                    b.HasKey("CustomerID");

                    b.ToTable("AccountBalances");
                });

            modelBuilder.Entity("TEC_KasinoAPI.Models.AccountGender", b =>
                {
                    b.Property<int>("GenderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderID"), 1L, 1);

                    b.Property<string>("GenderName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderID");

                    b.ToTable("AccountGenders");
                });

            modelBuilder.Entity("TEC_KasinoAPI.Models.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryID"), 1L, 1);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryID");

                    b.HasAlternateKey("CountryName")
                        .HasName("UN_Countries_CountryName");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("TEC_KasinoAPI.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPRNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("CountryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GenderID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasMaxLength(8)
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisterDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZipCodeID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.HasAlternateKey("CPRNumber")
                        .HasName("UN_Customers_CPRNumber");

                    b.HasAlternateKey("Email")
                        .HasName("UN_Customers_Email");

                    b.HasAlternateKey("PhoneNumber")
                        .HasName("UN_Customers_PhoneNumber");

                    b.HasIndex("CountryID");

                    b.HasIndex("GenderID");

                    b.HasIndex("ZipCodeID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TEC_KasinoAPI.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"), 1L, 1);

                    b.Property<string>("Amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BalanceCustomerID")
                        .HasColumnType("int");

                    b.Property<double>("CurrentBalance")
                        .HasColumnType("float");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionID");

                    b.HasIndex("BalanceCustomerID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("TEC_KasinoAPI.Models.ZipCode", b =>
                {
                    b.Property<int>("ZipCodeID")
                        .HasColumnType("int");

                    b.Property<string>("ZipCodeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZipCodeID");

                    b.ToTable("ZipCode");
                });

            modelBuilder.Entity("TEC_KasinoAPI.Models.AccountBalance", b =>
                {
                    b.HasOne("TEC_KasinoAPI.Models.Customer", null)
                        .WithOne("Acc_balance")
                        .HasForeignKey("TEC_KasinoAPI.Models.AccountBalance", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TEC_KasinoAPI.Models.Customer", b =>
                {
                    b.HasOne("TEC_KasinoAPI.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TEC_KasinoAPI.Models.AccountGender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TEC_KasinoAPI.Models.ZipCode", "ZipCode")
                        .WithMany()
                        .HasForeignKey("ZipCodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TEC_KasinoAPI.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("ID")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("ID"), 1L, 1);

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("CustomerID")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("datetime2");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Token")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ID");

                            b1.HasIndex("CustomerID");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner()
                                .HasForeignKey("CustomerID");
                        });

                    b.Navigation("Country");

                    b.Navigation("Gender");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ZipCode");
                });

            modelBuilder.Entity("TEC_KasinoAPI.Models.Transaction", b =>
                {
                    b.HasOne("TEC_KasinoAPI.Models.AccountBalance", "Balance")
                        .WithMany("Transactions")
                        .HasForeignKey("BalanceCustomerID");

                    b.Navigation("Balance");
                });

            modelBuilder.Entity("TEC_KasinoAPI.Models.AccountBalance", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TEC_KasinoAPI.Models.Customer", b =>
                {
                    b.Navigation("Acc_balance");
                });
#pragma warning restore 612, 618
        }
    }
}
